theme: jekyll-theme-slate

title: [The title of your site]
description: [A short description of your site's purpose]

show_downloads: true
github:
  zip_url: https://github.com/stokdenis/stokdenis.github.io/archive/master.zip
  tar_url: https://github.com/stokdenis/stokdenis.github.io/archive/master.tar
